# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('encrypted_data', models.BinaryField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('key_fingerprint', models.TextField()),
                ('data_fingerprint', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('user', 'User')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20)),
                ('encrypted_key', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('token', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('initialized', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(through='crypt_web.Sanction', to='crypt_web.Document')),
                ('teams', models.ManyToManyField(through='crypt_web.Membership', to='crypt_web.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.Team'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User'),
        ),
    ]
