# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('document_path', models.CharField(max_length=200)),
                ('document_version', models.UUIDField()),
                ('action', models.CharField(choices=[('create', 'Created'), ('read', 'Read'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('encrypted_data', models.BinaryField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('key_fingerprint', models.TextField()),
                ('data_fingerprint', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='crypt_web.Document')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('token', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('initialized', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(through='crypt_web.Sanction', to='crypt_web.Document')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User')),
            ],
        ),
        migrations.AddField(
            model_name='sanction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='crypt_web.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt_web.User'),
        ),
        migrations.AlterUniqueTogether(
            name='sanction',
            unique_together=set([('user', 'document')]),
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=set([('path', 'created')]),
        ),
    ]
